# Change these first
owner: DOEBELING # Your GitHub organization or username, where this repository lives
repo: status.doebeling.de # The name of this repository
user-agent: MopsFrank

sites:
  - name: 'Doebeling.de'
    url: https://Doebeling.de
    __dangerous__body_down_if_text_missing: 'projektbuero@doebeling.de'
    icon: https://Doebeling.de/favicon.ico
    maxResponseTime: 500
    skipDeleteIssues: true
    assignees:
    - ADoebeling  

  - name: 'Andreas.Doebeling.de'
    url: https://Andreas.Doebeling.de
    __dangerous__body_down_if_text_missing: 'A@Doebeling.de'
    icon: https://avatars.githubusercontent.com/u/10674780
    maxResponseTime: 500
    skipDeleteIssues: true
    assignees:
    - ADoebeling

  - name: 'Status.Doebeling.de'
    url: https://Status.Doebeling.de
    icon: https://status.doebeling.de/logo-192.png
    maxResponseTime: 500
    skipDeleteIssues: true
    assignees:
    - ADoebeling

  - name: 'Perepelytsina.de'
    url: http://Perepelytsina.de
    icon: https://avatars.githubusercontent.com/u/122738789
    maxResponseTime: 1000
    skipDeleteIssues: true
    expectedStatusCodes:
    - 301
    assignees:
    - NadiiaPer
    - ADoebeling

  - name: 'Nadiia.Perepelytsina.de'
    url: http://Nadiia.Perepelytsina.de
    icon: https://avatars.githubusercontent.com/u/122738789
    maxResponseTime: 1000
    expectedStatusCodes:
    - 301
    skipDeleteIssues: true
    assignees:
    - NadiiaPer
    - ADoebeling

  - name: 'Spruch-Archiv.com'
    url: https://Spruch-Archiv.com
    icon: https://www.spruch-archiv.com/favicon.ico
    __dangerous__body_down_if_text_missing: 'Herzlich Willkommen im Spruch-Archiv'
    maxResponseTime: 4000
    skipDeleteIssues: false
    assignees:
    - Xendiadyon
    - ADoebeling
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.doebeling.de
  robotsText: "User-agent: * \n Disallow: /"
  theme: light
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/10698845
  name: Status
  introTitle: "Status of our webpages"
  navbar:
    - title: Status
      href: /
    - title: DÖBELING Projektbüro
      href: https://Doebeling.de

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)<br>[Impressum](https://legal.doebeling.de/impressum), [Datenschutzerklärung](https://legal.doebeling.de/datenschutzerklaerung)

workflowSchedule:
  graphs: "23/30 * * * *"
  responseTime: "23/30 * * * *"
  staticSite: "0 1 * * *"
  summary: "23/30 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "MopsFrank [bot]"
  commitAuthorEmail: "mopsfrank.bot@doebeling.de"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
